name: Cypress Tests

on:
  push:
    branches:
      - main  

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Sprawdź kod
        uses: actions/checkout@v3
      
      - name: Konfiguracja Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      
      - name: Zainstaluj zależności
        run: npm ci
      
      - name: Uruchom testy Cypress
        uses: cypress-io/github-action@v3
